name: CICD - Backend
on:
  push: 
    branches: ["main"]
    paths: ["backend/**"]

env:
  PROJECT_ID: lab-develop-466614
  SERVICE_NAME: backend
  REGION: us-central1

jobs:
  build:
    runs-on: ubuntu-latest
    environment: poc

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar o SDK do gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: "beta"

      - name: Build e Push da imagem para o Artifact Registry
        run: |
          gcloud builds submit backend \
            --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar o SDK do gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: "beta"
          
      - name: Deploy no Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --memory 128Mi \
            --min-instances 0 \
            --max-instances 1 \
            --platform managed \
            --allow-unauthenticated